[build]
  base    = "website"
  publish = "website/build/textlint"
  command = "yarn run build"
[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--pure-lockfile --verbose"
